### ISSUE TITLE
Gimpscape PPA Release file not found

### ISSUE THREAD

**Issue by hid0** [devlovers-id/citramanik-qt#2]
E: The repository 'https://gimpscape.github.io/gimpscape-ppa/tools/focal ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
![image](https://user-images.githubusercontent.com/20245892/129676523-1b7ba02e-9b71-4c24-b2a8-c3b9fd24cfb7.png)

**Comment by raniaamina** [comment]
It fixed, would you re-check it and reconfirm this issue?

**Comment by Kexno** [comment]
Install via PPA will ask for Inkscape >= 0.1 though Inkscape snap & flatpak installed
`citramanik-qt : Depends: inkscape (>= 1.0) but it is not going to be installed`

**Comment by raniaamina** [comment]
By default Citramanik need Inkscape 1.0 or latest.
Some option that i can suggest to you is;
1. Install inkscape 1.0 or latest from PPA, it will solve dependencies
2. Use AppImage
3. If you still wanna use DEB package, you can download it [here](https://github.com/gimpscape/gimpscape-ppa/raw/master/focal/citramanik-qt_1.3.0_amd64.deb) manually then force install it (`sudo dpkg -i --force-all citramanik-qt_1.3.0_amd64.deb`). dwyor.

**Comment by hid0** [comment]
done, thanks bang @raniaamina
