### ISSUE TITLE
Citramanik (Appimage) closes immediately after clicking "Start Export" button

### ISSUE THREAD

**Issue by Kexno** [devlovers-id/citramanik-qt#3]
citramanik-qt-bionic-x86_64.AppImage & citramanik-qt-buster-x86_64.AppImage tested on KDE neon 5.22 with Inkscape 1.1 snap and flatpak installed

**Comment by raniaamina** [comment]
Hi @Kexno, we'll check it and ping you soon

**Comment by Kexno** [comment]
Log files with Inkscape Snap & Flatpak ver
[citraapp-20-08-21_19-26-12.log](https://github.com/devlovers-id/citramanik-qt/files/7021418/citraapp-20-08-21_19-26-12.log)
[citraapp-20-08-21_19-28-45.log](https://github.com/devlovers-id/citramanik-qt/files/7021419/citraapp-20-08-21_19-28-45.log)

**Comment by raniaamina** [comment]
Wolud you try to test run AppImage for Bullseye in your system?
https://getcitramanik.dev-is.my.id/releases/1.3.0/linux/citramanik-qt-bullseye-x86_64.AppImage/

**Comment by Kexno** [comment]
@raniaamina I have tested, Bullseye package has the same problem with Inkscape snap, but it works with Inkscape flatpak
[citraapp-20-08-21_23-22-51.log](https://github.com/devlovers-id/citramanik-qt/files/7022919/citraapp-20-08-21_23-22-51.log)

**Comment by raniaamina** [comment]
We still not support snap yet until this release, but you can use flatpak instead. 
So the case is closed.
