### ISSUE TITLE
Support for big files?

### ISSUE THREAD

**Issue by sevenzerotwo** [devlovers-id/citramanik-qt#7]
Hi! In before, thank you for your all hardwork on this Inkscape extended exporter tool, it's so useful! But, by the way, do you plan on supporting big files export? I have this error when i export my .pdf from my ~200mb .svg file (it contains some .ai imports and bitmaps) (also i guessed the big file error from "Huge input lookup" string)
![image](https://user-images.githubusercontent.com/80304158/145699740-fe898904-4588-4895-b1df-c11c57bb7d70.png)

I already open this issue on raniaamina's github before, the simple solution is making the embed files to linked. It works for my problem here (it reduced my .svg file to about ~10-20mb), but i wonder if there's another issue that this simple solution won't work (big size .svgs but not because of embed bitmaps)

**Comment by raniaamina** [comment]
Thanks for reporting it.
Some cloned object in inkscape sometimes also caused this error. So make if you've cloned object, unlink it first before exporting it with Citramanik. If still facing a problem, please send me sample of SVG file for testing purpose (just if possible).

**Comment by sevenzerotwo** [comment]
Alright, i gotta see if my big .svg having any cloned object, or i would try to export a .svg with cloned object with citramanik to test if the cloned object is the problem. Thank you, soon i'll back to this issue again after trying.

**Comment by sevenzerotwo** [comment]
Hi, it's been a month after this issue and until right now, seems like i don't getting any similar issues right now. I often do bitmap links right now in my workflows so my files are more smaller than before.

Thank you btw for your response, I'll close this issue.

**Comment by raniaamina** [comment]
It will solve in 1.3.2 release @sevenzerotwo
