### ISSUE TITLE
AppImage on Buster - Exit

### ISSUE THREAD

**Issue by canonex** [devlovers-id/citramanik-qt#9]
Hi,
using the AppImage - GLIBC 2.24 - on Buster, the software exits, without error, if it doesn't find Inkscape.

In detail:

1. install Inkscape as a FlatPack
2. I execute the appimage
3. I do the setup (load the file, exports etc...) but I forget to select "use flatpack".
4. the software exit without any warning, even on terminal

Would it be possible to automatically test the existence of flatpack if inkscape is not found in the bin?
Possibly with an error message only if it doesn't find both?

Thank you,
Riccardo

**Comment by raniaamina** [comment]
It should have been fixed
